"""Scoped dream consolidation draft service."""

from __future__ import annotations

import json
import re
from dataclasses import asdict, dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Literal, cast
from uuid import uuid4

from kubemin_agent.agent.memory.builtin import (
    BuiltinMemoryStore,
    MemoryAction,
    MemoryTarget,
    MemoryUpdateResult,
)
from kubemin_agent.agent.memory.scope import MemoryScope
from kubemin_agent.agent.memory.security import MemorySecurityError, scan_memory_text
from kubemin_agent.agent.memory.session_index import SessionSearchIndex, SessionTurn
from kubemin_agent.utils.helpers import sanitize_identifier

DreamTargetScope = Literal["personal", "team"]
DreamSource = Literal["manual", "threshold"]

_SIGNAL_PATTERN = re.compile(
    r"记住|偏好|喜欢|希望|规范|约定|团队|项目|工作区|remember|prefer|preference|"
    r"convention|standard|team|project|workspace",
    re.IGNORECASE,
)
_PERSONAL_PATTERN = re.compile(r"我|用户|偏好|喜欢|希望|prefer|preference", re.IGNORECASE)
_TEAM_PATTERN = re.compile(
    r"团队|规范|约定|项目|工作区|team|convention|standard|project|workspace",
    re.IGNORECASE,
)


@dataclass(frozen=True)
class DreamDueResult:
    """Dream threshold result for one scope."""

    due: bool
    reasons: tuple[str, ...]
    personal_turn_count: int = 0
    team_turn_count: int = 0


@dataclass(frozen=True)
class MemoryDreamDraftItem:
    """One candidate memory mutation generated by dream consolidation."""

    item_id: str
    target: str
    action: str
    content: str
    old_text: str = ""
    rationale: str = ""
    source_session_key: str = ""
    source_request_id: str = ""
    created_at: str = ""


@dataclass(frozen=True)
class MemoryDreamDraft:
    """Pending dream draft persisted for later approval."""

    draft_id: str
    target_scope: str
    source: str
    scope_metadata: dict[str, str]
    created_at: str
    items: list[MemoryDreamDraftItem]
    skipped_unsafe_count: int
    path: str


class MemoryDreamService:
    """Create and apply scoped memory consolidation drafts."""

    def __init__(
        self,
        root: Path,
        builtin: BuiltinMemoryStore,
        session_index: SessionSearchIndex,
        *,
        dream_turn_threshold: int = 20,
        dream_draft_top_k: int = 20,
    ) -> None:
        self.root = root.expanduser()
        self.builtin = builtin
        self.session_index = session_index
        self.dream_turn_threshold = max(1, dream_turn_threshold)
        self.dream_draft_top_k = max(1, dream_draft_top_k)
        self.pending_dir = self.root / "memory" / "dreams" / "pending"

    def check_due(self, scope: MemoryScope) -> DreamDueResult:
        """Check whether this scope should produce a dream draft."""
        reasons: list[str] = []
        for usage in self.builtin.usage(scope):
            if usage.warning:
                reasons.append(
                    f"{usage.target} memory usage is high "
                    f"({usage.usage_chars}/{usage.max_chars})"
                )

        personal_turn_count = self.session_index.count_turns(scope, scope_mode="personal")
        if personal_turn_count >= self.dream_turn_threshold:
            reasons.append(
                f"personal session turn threshold reached "
                f"({personal_turn_count}/{self.dream_turn_threshold})"
            )

        team_turn_count = 0
        if scope.has_team:
            team_turn_count = self.session_index.count_turns(scope, scope_mode="team")
            if team_turn_count >= self.dream_turn_threshold:
                reasons.append(
                    f"team session turn threshold reached "
                    f"({team_turn_count}/{self.dream_turn_threshold})"
                )

        return DreamDueResult(
            due=bool(reasons),
            reasons=tuple(reasons),
            personal_turn_count=personal_turn_count,
            team_turn_count=team_turn_count,
        )

    def create_draft(
        self,
        scope: MemoryScope,
        target_scope: DreamTargetScope = "personal",
        source: DreamSource = "manual",
    ) -> MemoryDreamDraft:
        """Create a pending dream draft without updating builtin memory."""
        if target_scope not in {"personal", "team"}:
            raise ValueError("target_scope must be one of: personal, team")
        if source not in {"manual", "threshold"}:
            raise ValueError("source must be one of: manual, threshold")
        if target_scope == "team" and not scope.has_team:
            raise ValueError("team_id is required for team dream drafts")

        created_at = self._now()
        draft_id = self._new_draft_id(scope, target_scope)
        turns = self.session_index.recent_turns(
            scope,
            top_k=self.dream_draft_top_k,
            scope_mode=target_scope,
        )
        items, skipped_unsafe_count = self._build_items(turns, target_scope)
        draft = MemoryDreamDraft(
            draft_id=draft_id,
            target_scope=target_scope,
            source=source,
            scope_metadata=scope.to_metadata(),
            created_at=created_at,
            items=items,
            skipped_unsafe_count=skipped_unsafe_count,
            path=str(self._draft_path(draft_id)),
        )
        self._write_draft(draft)
        return draft

    def apply_draft_item(self, draft_id: str, item_id: str) -> MemoryUpdateResult:
        """Apply one approved draft item to builtin memory."""
        records = self._read_records(draft_id)
        metadata = self._metadata_from_records(records)
        item = self._item_from_records(records, item_id)
        if item.get("applied_at"):
            raise ValueError("dream draft item was already applied")

        scope_data = metadata["scope"]
        if not isinstance(scope_data, dict):
            raise ValueError("dream draft scope is invalid")
        scope = MemoryScope(
            tenant_id=str(scope_data["tenant_id"]),
            user_id=str(scope_data["user_id"]),
            agent_name=str(scope_data["agent_name"]),
            team_id=str(scope_data.get("team_id", "")),
        )
        result = self.builtin.update(
            scope=scope,
            target=cast(MemoryTarget, str(item["target"])),
            action=cast(MemoryAction, str(item["action"])),
            content=str(item.get("content", "")),
            old_text=str(item.get("old_text", "")),
        )

        item["applied_at"] = self._now()
        self._write_records(draft_id, records)
        return result

    def _build_items(
        self,
        turns: list[SessionTurn],
        target_scope: str,
    ) -> tuple[list[MemoryDreamDraftItem], int]:
        items: list[MemoryDreamDraftItem] = []
        skipped_unsafe_count = 0
        for turn in turns:
            content = self._candidate_content(turn)
            if not content:
                continue
            target = self._target_for_content(content, target_scope)
            try:
                scan_memory_text(content)
            except MemorySecurityError:
                skipped_unsafe_count += 1
                continue
            items.append(
                MemoryDreamDraftItem(
                    item_id=f"item-{len(items) + 1}",
                    target=target,
                    action="add",
                    content=content,
                    rationale="recent scoped turn contains an explicit memory signal",
                    source_session_key=turn.session_key,
                    source_request_id=turn.request_id,
                    created_at=turn.created_at,
                )
            )
        return items, skipped_unsafe_count

    @staticmethod
    def _candidate_content(turn: SessionTurn) -> str:
        text = " ".join(turn.user_message.split())
        if not _SIGNAL_PATTERN.search(text):
            return ""
        if len(text) > 360:
            text = text[:357].rstrip() + "..."
        return text

    @staticmethod
    def _target_for_content(content: str, target_scope: str) -> str:
        if target_scope == "team":
            return "team" if _TEAM_PATTERN.search(content) else "team_memory"
        return "user" if _PERSONAL_PATTERN.search(content) else "memory"

    def _write_draft(self, draft: MemoryDreamDraft) -> None:
        records: list[dict[str, object]] = [
            {
                "kind": "draft",
                "draft_id": draft.draft_id,
                "target_scope": draft.target_scope,
                "source": draft.source,
                "scope": draft.scope_metadata,
                "created_at": draft.created_at,
                "skipped_unsafe_count": draft.skipped_unsafe_count,
            }
        ]
        records.extend({"kind": "item", **asdict(item)} for item in draft.items)
        self._write_records(draft.draft_id, records)

    def _read_records(self, draft_id: str) -> list[dict[str, object]]:
        path = self._draft_path(self._safe_draft_id(draft_id))
        if not path.exists():
            raise ValueError("dream draft was not found")
        records = [
            json.loads(line)
            for line in path.read_text(encoding="utf-8").splitlines()
            if line.strip()
        ]
        if not records:
            raise ValueError("dream draft is empty")
        return records

    def _write_records(self, draft_id: str, records: list[dict[str, object]]) -> None:
        path = self._draft_path(self._safe_draft_id(draft_id))
        self.pending_dir.mkdir(parents=True, exist_ok=True)
        text = "\n".join(json.dumps(record, ensure_ascii=False) for record in records)
        path.write_text(text + "\n", encoding="utf-8")

    @staticmethod
    def _metadata_from_records(records: list[dict[str, object]]) -> dict[str, object]:
        metadata = records[0]
        if metadata.get("kind") != "draft" or not isinstance(metadata.get("scope"), dict):
            raise ValueError("dream draft metadata is invalid")
        return metadata

    @staticmethod
    def _item_from_records(records: list[dict[str, object]], item_id: str) -> dict[str, object]:
        for record in records[1:]:
            if record.get("kind") == "item" and record.get("item_id") == item_id:
                return record
        raise ValueError("dream draft item was not found")

    def _draft_path(self, draft_id: str) -> Path:
        return self.pending_dir / f"{draft_id}.jsonl"

    @staticmethod
    def _safe_draft_id(draft_id: str) -> str:
        safe_id = sanitize_identifier(draft_id, default="")
        if not safe_id or safe_id != draft_id:
            raise ValueError("invalid dream draft id")
        return safe_id

    @staticmethod
    def _new_draft_id(scope: MemoryScope, target_scope: str) -> str:
        suffix = uuid4().hex[:8]
        return (
            f"dream-{scope.tenant_id}-{scope.team_id or scope.user_id}-"
            f"{scope.agent_name}-{target_scope}-{suffix}"
        )

    @staticmethod
    def _now() -> str:
        return datetime.now(UTC).isoformat(timespec="seconds").replace("+00:00", "Z")
